#!/bin/zsh


# Install Oh My ZSH
# =========================================================
ohmyzsh() {
  echo '\n🛠  Installing Oh My ZSH'
  OHMYZSH=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  sh -c "$(curl -fsSL ${ZSH_URL})"
  echo '✅  Done'
}


# Install Spaceship Theme
# =========================================================
spaceship() {
  echo '\n🛠  Install Spaceship Theme for Oh My ZSH'
  SPACESHIP_PATH=${ZSH_CUSTOM}/themes/spaceship-prompt
  if [[ ! -d "${SPACESHIP_PATH}" ]]; then
    git clone https://github.com/denysdovhan/spaceship-prompt.git ${SPACESHIP_PATH}
    ln -s ${SPACESHIP_PATH}/spaceship.zsh-theme ${ZSH_CUSTOM}/themes/spaceship.zsh-theme
    echo '✅  Done'
  else
    echo "✅  You've already have Spaceship installed"
    echo '🔃  Updating...'
    git --work-tree=${SPACESHIP_PATH} pull origin master
    echo '✅  Spaceship updated'
  fi
}

# "Restart to Windows" shortcut
# =========================================================
shortcuts () {
  echo -e '\n🛠  Creating "Restart to Windows" shortcuts'
  sudo cp -f ./shortcuts/windows.png \
    ./shortcuts/windows.sh \
    ./shortcuts/windows.desktop \
    /usr/share/applications/

  sudo chmod 644 /usr/share/applications/windows.{sh,desktop,png}
  sudo chmod -x /usr/share/applications/windows.desktop
  sudo chmod +x /usr/share/applications/windows.sh

  echo '✅  Done'
}


# Methods switch
# =========================================================
case $1 in
  ohmyzsh)   ohmyzsh;;
  spaceship) spaceship;;
  shortcuts) shortcuts;;
  *)         exit;;
esac

exit


# Install Oh My ZSH
# =========================================================
echo '[Dotfiles] Install Oh My ZSH...'
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install Spaceship Theme
# =========================================================
echo '[Dotfiles] Install Spaceship Theme...'
if [[ ! -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]]; then
  git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
  ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
fi

# Install zsh-autosuggestions
# =========================================================
echo '[Dotfiles] Install zsh-autosuggestions...'
if [[ ! -d "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]]; then
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# Disable screen lock and screen blackout
# =========================================================
gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.desktop.screensaver lock-enabled false

# "Restart to Windows" shortcut
# =========================================================
echo '[Dotfiles] Creating "Restart to Windows" shortcuts...'
sudo cp .local/share/applications/windows.png \
  .local/share/applications/windows.sh \
  .local/share/applications/windows.desktop \
  /usr/share/applications/

sudo chmod 644 /usr/share/applications/windows.{sh,desktop,png}
sudo chmod -x /usr/share/applications/windows.desktop
sudo chmod +x /usr/share/applications/windows.sh

# Installation finished sucessfully.
# =========================================================
echo -e '[Dotfiles] Installation finished sucessfully.'
source ~/.zshrc
