#!/bin/zsh

# Symlinking files
# =========================================================
echo '[Dotfiles] Symlinking files...'

rm ~/.aliases
rm ~/.profile
rm ~/.zshrc
rm ~/.vimrc
rm ~/.vim/basics.vim
rm ~/.vim/colors.vim
rm ~/.vim/keybindings.vim
rm ~/.vim/plugins.vim
rm ~/.config/terminator/config

ln -s $PWD/.aliases ~/.aliases
ln -s $PWD/.profile ~/.profile
ln -s $PWD/.zshrc ~/.zshrc
ln -s $PWD/.vimrc ~/.vimrc
ln -s $PWD/.vim/basics.vim ~/.vim/basics.vim
ln -s $PWD/.vim/colors.vim ~/.vim/colors.vim
ln -s $PWD/.vim/keybindings.vim ~/.vim/keybindings.vim
ln -s $PWD/.vim/plugins.vim ~/.vim/plugins.vim
ln -s $PWD/.config/terminator/config ~/.config/terminator/config

# "Restart to Windows" shortcut
echo '[Dotfiles] Creating "Restart to Windows" shortcuts...'
sudo cp .local/share/applications/windows.png \
  .local/share/applications/windows.sh \
  .local/share/applications/windows.desktop \
  /usr/share/applications/

sudo chmod 644 /usr/share/applications/windows.{sh,desktop,png}
sudo chmod -x /usr/share/applications/windows.desktop
sudo chmod +x /usr/share/applications/windows.sh

# Installation finished sucessfully.
# =========================================================
echo -e '[Dotfiles] Installation finished sucessfully.'
#source ~/.zshrc
