#!/bin/bash

user_symlinks() {
  # rm -rf Desktop Documentos Downloads Imagens Modelos Música Vídeos
  ln -s /mnt/windows/Users/thiago/Desktop /home/thiago/Desktop
  ln -s /mnt/windows/Users/thiago/Documents /home/thiago/Documentos
  ln -s /mnt/windows/Users/thiago/Downloads /home/thiago/Downloads
  ln -s /mnt/windows/Users/thiago/Pictures /home/thiago/Imagens
  ln -s /mnt/windows/Users/thiago/Modelos /home/thiago/Modelos
  ln -s /mnt/windows/Users/thiago/Music /home/thiago/Música
  ln -s /mnt/windows/Users/thiago/Videos /home/thiago/Vídeos
}
