#!/bin/bash

# Color constants
# =====================================================
# @see https://stackoverflow.com/a/28938235/1096219 👏

# Reset
export ColorOff='\033[0m'         # Text Reset

# Regular Colors
export Black='\033[0;30m'         # Black
export Red='\033[0;31m'           # Red
export Green='\033[0;32m'         # Green
export Yellow='\033[0;33m'        # Yellow
export Blue='\033[0;34m'          # Blue
export Purple='\033[0;35m'        # Purple
export Cyan='\033[0;36m'          # Cyan
export White='\033[0;37m'         # White

# Bold
export BBlack='\033[1;30m'        # Black
export BRed='\033[1;31m'          # Red
export BGreen='\033[1;32m'        # Green
export BYellow='\033[1;33m'       # Yellow
export BBlue='\033[1;34m'         # Blue
export BPurple='\033[1;35m'       # Purple
export BCyan='\033[1;36m'         # Cyan
export BWhite='\033[1;37m'        # White

# Underline
export UBlack='\033[4;30m'        # Black
export URed='\033[4;31m'          # Red
export UGreen='\033[4;32m'        # Green
export UYellow='\033[4;33m'       # Yellow
export UBlue='\033[4;34m'         # Blue
export UPurple='\033[4;35m'       # Purple
export UCyan='\033[4;36m'         # Cyan
export UWhite='\033[4;37m'        # White

# Background
export BgBlack='\033[40m'         # Black
export BgRed='\033[41m'           # Red
export BgGreen='\033[1;30;42m'    # Green
export BgYellow='\033[1;30;43m'   # Yellow
export BgBlue='\033[44m'          # Blue
export BgPurple='\033[1;30;45m'   # Purple
export BgCyan='\033[1;30;46m'     # Cyan
export BgWhite='\033[1;30;47m'    # White

# High Intensity
export IBlack='\033[0;90m'        # Black
export IRed='\033[0;91m'          # Red
export IGreen='\033[0;92m'        # Green
export IYellow='\033[0;93m'       # Yellow
export IBlue='\033[0;94m'         # Blue
export IPurple='\033[0;95m'       # Purple
export ICyan='\033[0;96m'         # Cyan
export IWhite='\033[0;97m'        # White

# Bold High Intensity
export BIBlack='\033[1;90m'       # Black
export BIRed='\033[1;91m'         # Red
export BIGreen='\033[1;92m'       # Green
export BIYellow='\033[1;93m'      # Yellow
export BIBlue='\033[1;94m'        # Blue
export BIPurple='\033[1;95m'      # Purple
export BICyan='\033[1;96m'        # Cyan
export BIWhite='\033[1;97m'       # White

# High Intensity backgrounds
export BgIBlack='\033[0;100m'     # Black
export BgIRed='\033[0;101m'       # Red
export BgIGreen='\033[1;30;102m'  # Green
export BgIYellow='\033[1;30;103m' # Yellow
export BgIBlue='\033[0;104m'      # Blue
export BgIPurple='\033[1;30;105m' # Purple
export BgICyan='\033[1;30;106m'   # Cyan
export BgIWhite='\033[1;30;107m'  # White

print_colors() {
  regular() {
    printf "${Black} %-9s ${ColorOff} " Black
    printf "${Red} %-9s ${ColorOff} " Red
    printf "${Green} %-9s ${ColorOff} " Green
    printf "${Yellow} %-9s ${ColorOff} " Yellow
    printf "${Blue} %-9s ${ColorOff} " Blue
    printf "${Purple} %-9s ${ColorOff} " Purple
    printf "${Cyan} %-9s ${ColorOff} " Cyan
    printf "${White} %-9s ${ColorOff} " White
    echo
  }

  bold() {
    printf "${BBlack} %-9s ${ColorOff} " BBlack
    printf "${BRed} %-9s ${ColorOff} " BRed
    printf "${BGreen} %-9s ${ColorOff} " BGreen
    printf "${BYellow} %-9s ${ColorOff} " BYellow
    printf "${BBlue} %-9s ${ColorOff} " BBlue
    printf "${BPurple} %-9s ${ColorOff} " BPurple
    printf "${BCyan} %-9s ${ColorOff} " BCyan
    printf "${BWhite} %-9s ${ColorOff} " BWhite
    echo
  }

  underline() {
    printf "${UBlack} %-9s ${ColorOff} " UBlack
    printf "${URed} %-9s ${ColorOff} " URed
    printf "${UGreen} %-9s ${ColorOff} " UGreen
    printf "${UYellow} %-9s ${ColorOff} " UYellow
    printf "${UBlue} %-9s ${ColorOff} " UBlue
    printf "${UPurple} %-9s ${ColorOff} " UPurple
    printf "${UCyan} %-9s ${ColorOff} " UCyan
    printf "${UWhite} %-9s ${ColorOff} " UWhite
    echo
  }

  background() {
    printf "${BgBlack} %-9s ${ColorOff} " BgBlack
    printf "${BgRed} %-9s ${ColorOff} " BgRed
    printf "${BgGreen} %-9s ${ColorOff} " BgGreen
    printf "${BgYellow} %-9s ${ColorOff} " BgYellow
    printf "${BgBlue} %-9s ${ColorOff} " BgBlue
    printf "${BgPurple} %-9s ${ColorOff} " BgPurple
    printf "${BgCyan} %-9s ${ColorOff} " BgCyan
    printf "${BgWhite} %-9s ${ColorOff} " BgWhite
    echo
  }

  high-intensity() {
    printf "${IBlack} %-9s ${ColorOff} " IBlack
    printf "${IRed} %-9s ${ColorOff} " IRed
    printf "${IGreen} %-9s ${ColorOff} " IGreen
    printf "${IYellow} %-9s ${ColorOff} " IYellow
    printf "${IBlue} %-9s ${ColorOff} " IBlue
    printf "${IPurple} %-9s ${ColorOff} " IPurple
    printf "${ICyan} %-9s ${ColorOff} " ICyan
    printf "${IWhite} %-9s ${ColorOff} " IWhite
    echo
  }

  bold-high-intensity() {
    printf "${BIBlack} %-9s ${ColorOff} " BIBlack
    printf "${BIRed} %-9s ${ColorOff} " BIRed
    printf "${BIGreen} %-9s ${ColorOff} " BIGreen
    printf "${BIYellow} %-9s ${ColorOff} " BIYellow
    printf "${BIBlue} %-9s ${ColorOff} " BIBlue
    printf "${BIPurple} %-9s ${ColorOff} " BIPurple
    printf "${BICyan} %-9s ${ColorOff} " BICyan
    printf "${BIWhite} %-9s ${ColorOff} " BIWhite
    echo
  }

  high-intensity-background() {
    printf "${BgIBlack} %-9s ${ColorOff} " BgIBlack
    printf "${BgIRed} %-9s ${ColorOff} " BgIRed
    printf "${BgIGreen} %-9s ${ColorOff} " BgIGreen
    printf "${BgIYellow} %-9s ${ColorOff} " BgIYellow
    printf "${BgIBlue} %-9s ${ColorOff} " BgIBlue
    printf "${BgIPurple} %-9s ${ColorOff} " BgIPurple
    printf "${BgICyan} %-9s ${ColorOff} " BgICyan
    printf "${BgIWhite} %-9s ${ColorOff} " BgIWhite
    echo
  }

  regular
  bold
  underline
  background
  high-intensity
  bold-high-intensity
  high-intensity-background
}