#!/bin/bash

# Define PATH environment variable in a more organized way.
# ------------------------------------------------------------------------------
PATHS=(
  '/home/linuxbrew/.linuxbrew/sbin'
  '/home/linuxbrew/.linuxbrew/bin'
  '/usr/local/sbin'
  '/usr/local/bin'
  '/usr/sbin'
  '/usr/bin'
  '/snap/bin'
  "${ANDROID_HOME}/tools"
  "${ANDROID_HOME}/platform-tools"
  "${KREW_ROOT:-${HOME}/.krew}/bin"
  "${HOME}/.local/lib/python3.10/site-packages"
  "${HOME}/.config/composer/vendor/bin"
  "${HOME}/.rbenv/bin"
  "${HOME}/.local/bin"
  "${HOME}/n/bin"
  "${HOME}/bin"
)

# Join array elements with delimiter
# @see https://zaiste.net/how_to_join_elements_of_an_array_in_bash/
# ------------------------------------------------------------------------------
join() {
  local IFS="$1"; shift; echo "$*"
}

PATH=$(join : "${PATHS[@]}")
export PATH
