#!/bin/bash

# Define PATH environment variable in a more organized way.
# ------------------------------------------------------------------------------
PATHS=(
  '/usr/local/sbin'
  '/usr/local/bin'
  '/usr/sbin'
  '/usr/bin'
  '/snap/bin'
  '/home/linuxbrew/.linuxbrew/bin'
  "$HOME/.config/composer/vendor/bin"
  "$HOME/.rbenv/versions/2.7.1/bin"
  "$HOME/.local/bin"
  "$HOME/n/bin"
)

# Join array elements with delimiter
# @see https://zaiste.net/how_to_join_elements_of_an_array_in_bash/
# ------------------------------------------------------------------------------
join() {
  local IFS="$1"
  shift
  echo "$*"
}

PATH=$(join : "${PATHS[@]}")

export PATH
export N_PREFIX="$HOME/n"