#!/bin/bash

# Powerlevel10k Zsh theme options
# ------------------------------------------------------------------------------
export POWERLEVEL9K_MODE='awesome-fontconfig'
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
export POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
