#!/bin/bash

# Spaceship Zsh theme options
# ------------------------------------------------------------------------------
export SPACESHIP_CHAR_SYMBOL=''
export SPACESHIP_DIR_SHOW=true
export SPACESHIP_DIR_TRUNC=0
export SPACESHIP_GIT_PREFIX=''
export SPACESHIP_GIT_SUFFIX=''
export SPACESHIP_GIT_STATUS_SHOW=true
export SPACESHIP_GIT_STATUS_COLOR='blue'
export SPACESHIP_GIT_STATUS_PREFIX=' '
export SPACESHIP_GIT_STATUS_SUFFIX=''
export SPACESHIP_TIME_SHOW=true
export SPACESHIP_PROMPT_ORDER=(dir host git line_sep jobs char)
export SPACESHIP_RPROMPT_ORDER=(time)