- name: 🎦 Ensures that Google Meet is using local icon
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Replace icon property using built-in lineinfile
      ansible.builtin.lineinfile:
        path: '{{ lookup("env", "HOME") }}/.local/share/applications/chrome-dbpkegghbgplfeaapbejbnfpbgnbjedf-Default.desktop'
        line: 'Icon={{ lookup("env", "HOME") }}/Imagens/Ícones/google-meet.png'
        regexp: '^Icon.*$'
